-- AI PATHFINDING PLATFORM DATABASE SCHEMA
-- Comprehensive schema for personalized learning path system

-- ============================================
-- USER PROFILES & AUTHENTICATION
-- ============================================

-- Extended user profiles with career goals and preferences
CREATE TABLE IF NOT EXISTS learner_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  location TEXT,
  
  -- Career Information
  current_role TEXT,
  target_role TEXT NOT NULL,
  experience_level TEXT CHECK (experience_level IN ('beginner', 'intermediate', 'advanced')),
  industry_preference TEXT[],
  
  -- Learning Preferences
  learning_style TEXT CHECK (learning_style IN ('visual', 'auditory', 'reading', 'kinesthetic', 'mixed')),
  weekly_hours_available INTEGER DEFAULT 10,
  preferred_learning_time TEXT CHECK (preferred_learning_time IN ('morning', 'afternoon', 'evening', 'flexible')),
  
  -- Background
  education_level TEXT,
  previous_skills TEXT[],
  languages TEXT[] DEFAULT ARRAY['English'],
  
  -- Profile Status
  onboarding_completed BOOLEAN DEFAULT FALSE,
  profile_completed_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initial skill assessment results
CREATE TABLE IF NOT EXISTS skill_assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  
  assessment_type TEXT CHECK (assessment_type IN ('initial', 'progress', 'final')),
  
  -- Technical Skills (0-100 score)
  programming_fundamentals INTEGER DEFAULT 0,
  web_development INTEGER DEFAULT 0,
  data_analysis INTEGER DEFAULT 0,
  mobile_development INTEGER DEFAULT 0,
  cloud_computing INTEGER DEFAULT 0,
  ai_ml INTEGER DEFAULT 0,
  
  -- Soft Skills (0-100 score)
  problem_solving INTEGER DEFAULT 0,
  communication INTEGER DEFAULT 0,
  teamwork INTEGER DEFAULT 0,
  adaptability INTEGER DEFAULT 0,
  
  -- Overall Score
  overall_score INTEGER GENERATED ALWAYS AS (
    (programming_fundamentals + web_development + data_analysis + 
     mobile_development + cloud_computing + ai_ml + 
     problem_solving + communication + teamwork + adaptability) / 10
  ) STORED,
  
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- SKILLS & COMPETENCIES
-- ============================================

-- Master list of skills/competencies
CREATE TABLE IF NOT EXISTS skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL, -- 'technical', 'soft', 'domain'
  subcategory TEXT,
  description TEXT,
  
  -- Market Data
  demand_score INTEGER DEFAULT 50, -- 0-100, how in-demand this skill is
  average_salary_impact DECIMAL(10,2), -- naira impact on salary
  
  -- Learning Metadata
  difficulty_level TEXT CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced', 'expert')),
  estimated_hours INTEGER, -- hours to achieve proficiency
  
  prerequisites UUID[], -- array of skill IDs that should be learned first
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Job roles and their required skills
CREATE TABLE IF NOT EXISTS job_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  category TEXT, -- 'software', 'data', 'design', 'product', etc.
  
  -- Market Data
  average_salary_min DECIMAL(12,2),
  average_salary_max DECIMAL(12,2),
  job_openings_count INTEGER DEFAULT 0,
  growth_rate DECIMAL(5,2), -- percentage
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Skills required for each job role
CREATE TABLE IF NOT EXISTS job_role_skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_role_id UUID REFERENCES job_roles(id) ON DELETE CASCADE,
  skill_id UUID REFERENCES skills(id) ON DELETE CASCADE,
  
  importance TEXT CHECK (importance IN ('required', 'preferred', 'nice-to-have')),
  proficiency_level TEXT CHECK (proficiency_level IN ('basic', 'intermediate', 'advanced', 'expert')),
  
  UNIQUE(job_role_id, skill_id)
);

-- ============================================
-- LEARNING PATHS
-- ============================================

-- Personalized learning paths generated by AI
CREATE TABLE IF NOT EXISTS learning_paths (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  job_role_id UUID REFERENCES job_roles(id),
  
  path_name TEXT NOT NULL,
  description TEXT,
  
  -- Path Characteristics
  difficulty_level TEXT CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced', 'custom')),
  estimated_duration_weeks INTEGER,
  total_estimated_hours INTEGER,
  
  -- AI Generation Metadata
  generation_algorithm TEXT DEFAULT 'v1.0',
  personalization_factors JSONB, -- stores factors used in path creation
  
  -- Status
  status TEXT CHECK (status IN ('draft', 'active', 'paused', 'completed', 'abandoned')) DEFAULT 'active',
  
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  last_accessed_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- COURSES & CONTENT
-- ============================================

-- Course catalog (aggregated from multiple platforms)
CREATE TABLE IF NOT EXISTS courses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Basic Info
  title TEXT NOT NULL,
  description TEXT,
  platform TEXT, -- 'coursera', 'udemy', 'edx', 'youtube', 'custom', etc.
  platform_course_id TEXT,
  url TEXT,
  
  -- Content Details
  instructor TEXT,
  duration_hours DECIMAL(5,1),
  difficulty_level TEXT CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced')),
  language TEXT DEFAULT 'English',
  
  -- Quality Metrics
  rating DECIMAL(3,2),
  reviews_count INTEGER DEFAULT 0,
  completion_rate DECIMAL(5,2),
  
  -- Cost
  is_free BOOLEAN DEFAULT FALSE,
  cost_usd DECIMAL(10,2),
  cost_ngn DECIMAL(12,2),
  
  -- Content Type
  content_type TEXT[], -- 'video', 'text', 'interactive', 'project', 'quiz'
  certificate_available BOOLEAN DEFAULT FALSE,
  
  -- Status
  is_active BOOLEAN DEFAULT TRUE,
  last_updated TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Skills taught by each course
CREATE TABLE IF NOT EXISTS course_skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  skill_id UUID REFERENCES skills(id) ON DELETE CASCADE,
  
  proficiency_gain TEXT CHECK (proficiency_gain IN ('basic', 'intermediate', 'advanced')),
  
  UNIQUE(course_id, skill_id)
);

-- Modules/lessons within courses
CREATE TABLE IF NOT EXISTS course_modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  
  module_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  duration_hours DECIMAL(4,1),
  
  content_url TEXT,
  resources JSONB, -- links, downloads, etc.
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- PATH STEPS & SEQUENCING
-- ============================================

-- Individual steps in a learning path
CREATE TABLE IF NOT EXISTS path_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learning_path_id UUID REFERENCES learning_paths(id) ON DELETE CASCADE,
  
  step_number INTEGER NOT NULL,
  step_type TEXT CHECK (step_type IN ('course', 'project', 'assessment', 'milestone')),
  
  -- Step Content
  course_id UUID REFERENCES courses(id),
  title TEXT NOT NULL,
  description TEXT,
  estimated_hours DECIMAL(5,1),
  
  -- Requirements
  prerequisites UUID[], -- other step IDs that must be completed first
  target_skills UUID[], -- skill IDs this step develops
  
  -- Status
  is_mandatory BOOLEAN DEFAULT TRUE,
  is_unlocked BOOLEAN DEFAULT FALSE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- PROGRESS TRACKING
-- ============================================

-- Overall progress on learning paths
CREATE TABLE IF NOT EXISTS path_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  learning_path_id UUID REFERENCES learning_paths(id) ON DELETE CASCADE,
  
  -- Progress Metrics
  steps_completed INTEGER DEFAULT 0,
  steps_total INTEGER,
  progress_percentage DECIMAL(5,2) DEFAULT 0,
  
  hours_spent DECIMAL(8,1) DEFAULT 0,
  hours_estimated INTEGER,
  
  -- Velocity Metrics (for SAV calculation)
  avg_hours_per_week DECIMAL(5,1),
  completion_velocity DECIMAL(5,2), -- steps per week
  
  -- Engagement
  current_streak_days INTEGER DEFAULT 0,
  longest_streak_days INTEGER DEFAULT 0,
  last_activity_date DATE,
  
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Detailed progress on individual steps
CREATE TABLE IF NOT EXISTS step_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  path_step_id UUID REFERENCES path_steps(id) ON DELETE CASCADE,
  
  status TEXT CHECK (status IN ('not_started', 'in_progress', 'completed', 'skipped')) DEFAULT 'not_started',
  
  -- Progress Details
  progress_percentage DECIMAL(5,2) DEFAULT 0,
  time_spent_hours DECIMAL(6,2) DEFAULT 0,
  
  -- Completion Data
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  
  -- Engagement Metrics
  sessions_count INTEGER DEFAULT 0,
  last_accessed_at TIMESTAMP WITH TIME ZONE,
  
  notes TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Learning sessions (for detailed analytics)
CREATE TABLE IF NOT EXISTS learning_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  path_step_id UUID REFERENCES path_steps(id),
  
  session_start TIMESTAMP WITH TIME ZONE NOT NULL,
  session_end TIMESTAMP WITH TIME ZONE,
  duration_minutes INTEGER,
  
  activities JSONB, -- detailed session activities
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- ASSESSMENTS & CERTIFICATIONS
-- ============================================

-- Skill assessments and quizzes
CREATE TABLE IF NOT EXISTS assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  title TEXT NOT NULL,
  description TEXT,
  assessment_type TEXT CHECK (assessment_type IN ('quiz', 'project', 'coding_challenge', 'practical')),
  
  skill_id UUID REFERENCES skills(id),
  difficulty_level TEXT CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced')),
  
  time_limit_minutes INTEGER,
  passing_score INTEGER DEFAULT 70,
  
  questions JSONB, -- assessment content
  
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Assessment results
CREATE TABLE IF NOT EXISTS assessment_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  assessment_id UUID REFERENCES assessments(id),
  path_step_id UUID REFERENCES path_steps(id),
  
  score INTEGER,
  max_score INTEGER,
  percentage DECIMAL(5,2),
  passed BOOLEAN,
  
  time_taken_minutes INTEGER,
  attempt_number INTEGER DEFAULT 1,
  
  answers JSONB,
  feedback JSONB,
  
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Certificates earned
CREATE TABLE IF NOT EXISTS certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  
  certificate_type TEXT CHECK (certificate_type IN ('course', 'path', 'skill', 'platform')),
  certificate_name TEXT NOT NULL,
  
  course_id UUID REFERENCES courses(id),
  learning_path_id UUID REFERENCES learning_paths(id),
  skill_id UUID REFERENCES skills(id),
  
  issued_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  certificate_url TEXT,
  verification_code TEXT UNIQUE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- AI RECOMMENDATIONS & ANALYTICS
-- ============================================

-- AI-generated recommendations for path adjustments
CREATE TABLE IF NOT EXISTS path_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  learning_path_id UUID REFERENCES learning_paths(id),
  
  recommendation_type TEXT CHECK (recommendation_type IN ('add_course', 'skip_course', 'adjust_pace', 'focus_skill', 'take_break')),
  
  title TEXT NOT NULL,
  description TEXT,
  reasoning TEXT, -- AI explanation
  
  suggested_action JSONB,
  priority TEXT CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  
  -- Status
  status TEXT CHECK (status IN ('pending', 'accepted', 'rejected', 'expired')) DEFAULT 'pending',
  expires_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Key metrics for dashboard (Job Readiness Score, SAV, PCR)
CREATE TABLE IF NOT EXISTS learner_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  learner_id UUID REFERENCES learner_profiles(id) ON DELETE CASCADE,
  learning_path_id UUID REFERENCES learning_paths(id),
  
  -- Job Readiness Score (JRS) - 0-100
  job_readiness_score INTEGER DEFAULT 0,
  jrs_breakdown JSONB, -- detailed breakdown by skill category
  
  -- Skill Acquisition Velocity (SAV) - skills per week
  skill_acquisition_velocity DECIMAL(5,2) DEFAULT 0,
  sav_trend JSONB, -- historical trend data
  
  -- Path Completion Rate (PCR) - percentage
  path_completion_rate DECIMAL(5,2) DEFAULT 0,
  
  -- Additional Metrics
  learning_efficiency DECIMAL(5,2), -- actual vs estimated time ratio
  engagement_score INTEGER, -- 0-100
  consistency_score INTEGER, -- 0-100
  
  -- Predictions
  predicted_completion_date DATE,
  predicted_job_ready_date DATE,
  
  calculated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- PLATFORM ANALYTICS
-- ============================================

-- Aggregate platform metrics for dashboard
CREATE TABLE IF NOT EXISTS platform_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_date DATE NOT NULL UNIQUE,
  
  -- User Metrics
  total_learners INTEGER DEFAULT 0,
  active_learners INTEGER DEFAULT 0,
  new_learners INTEGER DEFAULT 0,
  
  -- Engagement Metrics
  avg_session_duration_minutes DECIMAL(6,2),
  total_learning_hours DECIMAL(10,2),
  avg_weekly_hours DECIMAL(5,2),
  
  -- Performance Metrics
  avg_job_readiness_score DECIMAL(5,2),
  avg_skill_acquisition_velocity DECIMAL(5,2),
  avg_path_completion_rate DECIMAL(5,2),
  
  -- Outcome Metrics
  paths_completed INTEGER DEFAULT 0,
  certificates_issued INTEGER DEFAULT 0,
  skills_acquired INTEGER DEFAULT 0,
  
  -- Demographics
  gender_distribution JSONB,
  location_distribution JSONB,
  age_distribution JSONB,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX idx_learner_profiles_user_id ON learner_profiles(user_id);
CREATE INDEX idx_learner_profiles_target_role ON learner_profiles(target_role);

CREATE INDEX idx_learning_paths_learner_id ON learning_paths(learner_id);
CREATE INDEX idx_learning_paths_status ON learning_paths(status);

CREATE INDEX idx_path_steps_learning_path_id ON path_steps(learning_path_id);
CREATE INDEX idx_path_steps_course_id ON path_steps(course_id);

CREATE INDEX idx_step_progress_learner_id ON step_progress(learner_id);
CREATE INDEX idx_step_progress_status ON step_progress(status);

CREATE INDEX idx_courses_platform ON courses(platform);
CREATE INDEX idx_courses_difficulty ON courses(difficulty_level);
CREATE INDEX idx_courses_active ON courses(is_active);

CREATE INDEX idx_skills_category ON skills(category);
CREATE INDEX idx_skills_demand ON skills(demand_score DESC);

CREATE INDEX idx_learner_metrics_learner_id ON learner_metrics(learner_id);
CREATE INDEX idx_learner_metrics_jrs ON learner_metrics(job_readiness_score DESC);

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables
ALTER TABLE learner_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE path_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE path_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE learner_metrics ENABLE ROW LEVEL SECURITY;

-- Learners can only see their own data
CREATE POLICY learner_profiles_policy ON learner_profiles
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY skill_assessments_policy ON skill_assessments
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY learning_paths_policy ON learning_paths
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY path_progress_policy ON path_progress
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY step_progress_policy ON step_progress
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY learning_sessions_policy ON learning_sessions
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY assessment_results_policy ON assessment_results
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY certificates_policy ON certificates
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY path_recommendations_policy ON path_recommendations
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

CREATE POLICY learner_metrics_policy ON learner_metrics
  FOR ALL USING (learner_id IN (SELECT id FROM learner_profiles WHERE user_id = auth.uid()));

-- Public read access for reference data
CREATE POLICY skills_read_policy ON skills FOR SELECT USING (true);
CREATE POLICY job_roles_read_policy ON job_roles FOR SELECT USING (true);
CREATE POLICY courses_read_policy ON courses FOR SELECT USING (is_active = true);
CREATE POLICY assessments_read_policy ON assessments FOR SELECT USING (is_active = true);

-- ============================================
-- FUNCTIONS FOR CALCULATIONS
-- ============================================

-- Calculate Job Readiness Score
CREATE OR REPLACE FUNCTION calculate_job_readiness_score(
  p_learner_id UUID,
  p_job_role_id UUID
) RETURNS INTEGER AS $$
DECLARE
  v_score INTEGER := 0;
  v_required_skills INTEGER;
  v_acquired_skills INTEGER;
BEGIN
  -- Count required skills for target job role
  SELECT COUNT(*) INTO v_required_skills
  FROM job_role_skills
  WHERE job_role_id = p_job_role_id AND importance = 'required';
  
  -- Count acquired skills from learner's progress
  -- This is a simplified version - actual implementation would check skill proficiency
  SELECT COUNT(DISTINCT skill_id) INTO v_acquired_skills
  FROM course_skills cs
  JOIN path_steps ps ON cs.course_id = ps.course_id
  JOIN step_progress sp ON ps.id = sp.path_step_id
  WHERE sp.learner_id = p_learner_id 
    AND sp.status = 'completed'
    AND cs.skill_id IN (
      SELECT skill_id FROM job_role_skills 
      WHERE job_role_id = p_job_role_id AND importance = 'required'
    );
  
  -- Calculate percentage
  IF v_required_skills > 0 THEN
    v_score := (v_acquired_skills * 100) / v_required_skills;
  END IF;
  
  RETURN LEAST(v_score, 100); -- Cap at 100
END;
$$ LANGUAGE plpgsql;

-- Update learner metrics (called after progress updates)
CREATE OR REPLACE FUNCTION update_learner_metrics(p_learner_id UUID)
RETURNS VOID AS $$
DECLARE
  v_learning_path_id UUID;
  v_job_role_id UUID;
  v_jrs INTEGER;
  v_sav DECIMAL(5,2);
  v_pcr DECIMAL(5,2);
BEGIN
  -- Get active learning path
  SELECT id, job_role_id INTO v_learning_path_id, v_job_role_id
  FROM learning_paths
  WHERE learner_id = p_learner_id AND status = 'active'
  LIMIT 1;
  
  IF v_learning_path_id IS NOT NULL THEN
    -- Calculate JRS
    v_jrs := calculate_job_readiness_score(p_learner_id, v_job_role_id);
    
    -- Calculate SAV (skills acquired per week)
    SELECT COALESCE(
      (COUNT(DISTINCT cs.skill_id) / 
       NULLIF(EXTRACT(WEEK FROM AGE(NOW(), MIN(sp.started_at))), 0)),
      0
    ) INTO v_sav
    FROM step_progress sp
    JOIN path_steps ps ON sp.path_step_id = ps.id
    JOIN course_skills cs ON ps.course_id = cs.course_id
    WHERE sp.learner_id = p_learner_id 
      AND sp.status = 'completed'
      AND sp.started_at IS NOT NULL;
    
    -- Calculate PCR
    SELECT COALESCE(progress_percentage, 0) INTO v_pcr
    FROM path_progress
    WHERE learner_id = p_learner_id 
      AND learning_path_id = v_learning_path_id;
    
    -- Insert or update metrics
    INSERT INTO learner_metrics (
      learner_id,
      learning_path_id,
      job_readiness_score,
      skill_acquisition_velocity,
      path_completion_rate,
      calculated_at
    ) VALUES (
      p_learner_id,
      v_learning_path_id,
      v_jrs,
      v_sav,
      v_pcr,
      NOW()
    )
    ON CONFLICT (learner_id, learning_path_id) 
    DO UPDATE SET
      job_readiness_score = v_jrs,
      skill_acquisition_velocity = v_sav,
      path_completion_rate = v_pcr,
      calculated_at = NOW();
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Add unique constraint for learner_metrics
ALTER TABLE learner_metrics ADD CONSTRAINT unique_learner_path 
  UNIQUE (learner_id, learning_path_id);

COMMENT ON TABLE learner_profiles IS 'Extended user profiles with career goals and learning preferences';
COMMENT ON TABLE learning_paths IS 'AI-generated personalized learning paths for each learner';
COMMENT ON TABLE learner_metrics IS 'Key metrics: JRS, SAV, PCR for dashboard display';
