-- ==========================================
-- NORTH: AI PATHFINDING BACKEND SCHEMA
-- ==========================================

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. JOB ROLES (Public Catalog)
CREATE TABLE IF NOT EXISTS job_roles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(255),
    description TEXT,
    avg_salary_min INTEGER,
    avg_salary_max INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. LEARNER PROFILES (User Data)
CREATE TABLE IF NOT EXISTS learner_profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL, -- Links to auth.users (if using Supabase Auth)
    full_name VARCHAR(255),
    target_role TEXT,
    experience_level VARCHAR(50), -- 'beginner', 'intermediate', 'advanced'
    onboarding_completed BOOLEAN DEFAULT FALSE,
    profile_completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. LEARNING PATHS (The "North" Star)
CREATE TABLE IF NOT EXISTS learning_paths (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    learner_id UUIDREFERENCES learner_profiles(id) ON DELETE CASCADE,
    job_role_id UUID REFERENCES job_roles(id),
    path_name VARCHAR(255) NOT NULL,
    description TEXT,
    difficulty_level VARCHAR(50), -- 'custom', 'beginner', etc.
    status VARCHAR(50) DEFAULT 'active', -- 'active', 'completed', 'archived'
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. PATH STEPS (Milestones generated by AI)
CREATE TABLE IF NOT EXISTS path_steps (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    learning_path_id UUID REFERENCES learning_paths(id) ON DELETE CASCADE,
    step_number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    step_type VARCHAR(50) DEFAULT 'module', -- 'module', 'project', 'assessment'
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'in_progress', 'completed'
    estimated_hours INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE job_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE learner_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE path_steps ENABLE ROW LEVEL SECURITY;

-- POLICIES
-- Job Roles: Everyone can read
CREATE POLICY "Public can read job roles" ON job_roles FOR SELECT USING (true);

-- Learner Profiles: Users can only read/write their own
CREATE POLICY "Users can read own profile" ON learner_profiles
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON learner_profiles
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own profile" ON learner_profiles
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Learning Paths: Users can read own paths via learner_profile
CREATE POLICY "Users can read own paths" ON learning_paths
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM learner_profiles
            WHERE id = learning_paths.learner_id
            AND user_id = auth.uid()
        )
    );
CREATE POLICY "Users can insert own paths" ON learning_paths
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM learner_profiles
            WHERE id = learning_paths.learner_id
            AND user_id = auth.uid()
        )
    );

-- Path Steps: Inherit access from Learning Path
CREATE POLICY "Users can read own steps" ON path_steps
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM learning_paths
            JOIN learner_profiles ON learning_paths.learner_id = learner_profiles.id
            WHERE learning_paths.id = path_steps.learning_path_id
            AND learner_profiles.user_id = auth.uid()
        )
    );

-- ==========================================
-- SEED DATA (Job Roles)
-- ==========================================

INSERT INTO job_roles (title, category, description, avg_salary_min, avg_salary_max) 
VALUES 
('Frontend Developer', 'Engineering', 'Builds user interfaces using React, Vue, or Angular.', 70000, 120000),
('Backend Engineer', 'Engineering', 'Designs server-side logic, databases, and APIs.', 80000, 140000),
('Full Stack Developer', 'Engineering', 'MAsters both frontend and backend technologies.', 90000, 150000),
('Data Scientist', 'Data', 'Analyzes complex data to help make business decisions.', 95000, 160000),
('Product Manager', 'Product', 'Oversees product development from conception to launch.', 85000, 150000),
('UI/UX Designer', 'Design', 'Designs intuitive and beautiful user experiences.', 65000, 115000)
ON CONFLICT (title) DO NOTHING;
